### PR TITLE
Update to NLopt version 2.7.1

### PR DESCRIPTION
**Pull request by astamm**

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! I'm not sure how you built these, but I rather go though our official build CI. I have updated the formula here and will publish the binary artifacts here in a minute when it's done: https://github.com/r-windows/rtools-packages/commit/b1f3f6e41e01f5eb8c4d1af501d62c5d39c3a1cb

**Comment by astamm** [comment]
Thanks @jeroen!
I had `cmake` generate them on the winbuilder release machine and grab them from the artifacts.
But, by all means, use your official build CI, I won't mind.
Thank you very much.

**Comment by astamm** [comment]
Will it also provide the new release that I can use for downloading from `nloptr`?

**Comment by astamm** [comment]
Thanks. I see I can now install it with `pacman`.
@jeroen : Do you think you could update the release on this repo as well, so that I can just download from (https://github.com/rwinlib/nlopt/archive/refs/tags/v2.7.1.tar.gz), which is what you contributed a couple of years ago with the 2.4.2 version?

**Comment by jeroen** [comment]
I'll update this repo in a minute :)

**Comment by jeroen** [comment]
Superseded by https://github.com/rwinlib/nlopt/releases/tag/v2.7.1

**Pull request closed without merging**
